<!DOCTYPE html>
<html lang="en">
<?js
 let require = process.mainModule.require;
 let package = require(obj.env.pwd + "/package.json");
 console.log(package);
?>
<head>
    <meta charset="utf-8">
    <title><?js= package.name ?> <?js= package.version ?> Documentation</title>
    <script src="scripts/prettify.js"> </script>
    <script src="scripts/lang-css.js"> </script>
    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link type="text/css" rel="stylesheet" href="styles/tomorrow.min.css">
    <link type="text/css" rel="stylesheet" href="styles/jsdoc-default.css">
    <style>
      #main section > article h1:first-of-type { margin-top: unset; margin-left: unset; margin-bottom: 46px;}
    </style>
</head>

<body>

  <div id="main">
    <?js if(title != "Home") { ?><h1 class="page-title"><?js= title ?></h1><?js } ?>
    <?js content = content.replace('<h3> </h3>', ''); ?>
    <?js= content ?>
  </div>

<nav>
    <?js= this.nav ?>
</nav>

<br class="clear">

<footer>
  <a href="https://www.npmjs.com/package/<?js= package.name ?>/v/<?js= package.version ?>">
    <?js= package.name ?> <?js= package.version ?>
  </a>
  documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc <?js= env.version.number ?></a><?js if(env.conf.templates && env.conf.templates.default && env.conf.templates.default.includeDate !== false) { ?> on <?js= (new Date()) ?><?js } ?>
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
</body>
</html>
